# Installs wheels from the latest run of a specified workflow
name: install-wheels
description: Install latest wheels from a specified workflow using a custom wildcard
inputs:
  workflow:
    description: Name of the workflow to install wheels from
    default: Triton wheels
  repository:
    description: Repository name with owner
    default: intel/intel-xpu-backend-for-triton
  wheels_pattern:
    # Example of specifying only some packages to install: {intel_extension_for_pytorch-*,torch-*}
    description: Pattern to match the wheel files to download
    default: '*'
  gh_token:
    description: GitHub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Install wheels from specified workflow artifacts
      shell: bash -x
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
      run: |
        WORKFLOW_ID=$(gh run list -w "${{ inputs.workflow }}" -R ${{ inputs.repository }} --json databaseId | jq '.[0].databaseId')
        PYTHON_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
        TEMP_DIR=`mktemp -d`
        pushd ${TEMP_DIR}
        gh run download ${WORKFLOW_ID} -R ${{ inputs.repository }} --pattern "wheels-py${PYTHON_VERSION}*"
        cd wheels-py${PYTHON_VERSION}*
        pip install ${{ inputs.wheels_pattern }}
        popd
        rm -rf ${TEMP_DIR}
