name: setup-no-op-ipex
description: Create a no-op package that imitates installed IPEX
runs:
  using: "composite"
  steps:
    - name: Create and install no-op IPEX
      shell: bash
      run: |
        mkdir intel-extension-for-pytorch
        cd intel-extension-for-pytorch
        cat > setup.py <<EOF
        from setuptools import setup

        name = "intel-extension-for-pytorch"
        version = "2.4.0+dummy_no-op"

        setup(
            name=name,
            version=version,
            description="No-op Intel Extension for PyTorch"
        )
        EOF
        mkdir intel_extension_for_pytorch
        echo '__version__ = "2.4.0+dummy_no-op"' > intel_extension_for_pytorch/__init__.py
        pip install -e .
