# Clones PyTorch (or loads from cache) to directory "pytorch".
# Uses the existing Python.
# Sets the following environment variables:
# * PYTORCH_REPO
# * PYTORCH_COMMIT_ID
name: setup-pytorch
description: Build and install PyTorch wheels
inputs:
  oneapi:
    description: Directory with oneAPI BaseKit
    default: ~/intel/oneapi
  repository:
    description: Repository name with owner
    default: Stonepia/pytorch
runs:
  using: "composite"
  steps:
    - name: Identify commit id
      shell: bash
      run: |
        PYTORCH_COMMIT_ID="$(<.github/pins/pytorch.txt)"
        echo "PYTORCH_REPO=${{ inputs.repository }}" >> "$GITHUB_ENV"
        echo "PYTORCH_COMMIT_ID=$PYTORCH_COMMIT_ID" >> "$GITHUB_ENV"

    - name: Identify Python version
      shell: bash
      run: |
        if [[ -z "$PYTHON_VERSION" ]]; then
          PYTHON_VERSION="$(python -c 'import sys; print(f"{sys.version_info[0]}.{ sys.version_info[1]}")')"
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
        fi

    # PyTorch build process expects Intel oneAPI in /opt/intel/oneapi
    # https://github.com/Stonepia/pytorch/blob/c9153c96f547f269581743e7443aa86d7e003505/cmake/Modules/FindMKL.cmake#L44
    - name: Set up oneAPI
      shell: bash
      run: |
        if [[ -d /opt/intel/oneapi ]]; then
          exit 0
        fi
        if [[ -L /opt/intel/oneapi ]]; then
          exit 0
        fi
        sudo mkdir -p /opt/intel
        sudo ln -sfT ${{ inputs.oneapi }} /opt/intel/oneapi

    - name: Load PyTorch from a cache
      id: pytorch-cache
      uses: ./.github/actions/load
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: "4"
      with:
        path: pytorch
        key: pytorch-$PYTHON_VERSION-$PYTORCH_COMMIT_ID-$CACHE_NUMBER

    - name: Clone PyTorch repository
      if: ${{ steps.pytorch-cache.outputs.status == 'miss' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ env.PYTORCH_COMMIT_ID }}
        submodules: recursive
        path: pytorch

    - name: Build PyTorch
      if: ${{ steps.pytorch-cache.outputs.status == 'miss' }}
      shell: bash
      run: |
        source ${{ inputs.oneapi }}/setvars.sh
        cd pytorch
        pip install wheel
        pip install -r requirements.txt
        python setup.py bdist_wheel

    - name: Install PyTorch
      shell: bash
      run: |
        source ${{ inputs.oneapi }}/setvars.sh
        pip install pytorch/dist/*.whl
        python -c "import torch;print(torch.__version__)"

    - name: Save PyTorch to a cache
      if: ${{ steps.pytorch-cache.outputs.status == 'miss' }}
      uses: ./.github/actions/save
      with:
        path: ${{ steps.pytorch-cache.outputs.path }}
        dest: ${{ steps.pytorch-cache.outputs.dest }}
