# Clones IPEX (or loads from cache) to directory "intel-extension-for-pytorch".
# Uses the existing Python, requires PyTorch.
# Sets the following environment variables:
# * IPEX_REPO
# * IPEX_COMMIT_ID
# * IPEX_VERSION
name: setup-ipex
description: Build and install IPEX wheels
inputs:
  oneapi:
    description: Directory with oneAPI BaseKit
    default: /opt/intel/oneapi
  repository:
    description: Repository name with owner
    default: intel/intel-extension-for-pytorch
runs:
  using: "composite"
  steps:
    - name: Identify commit id
      shell: bash
      run: |
        IPEX_COMMIT_ID="$(<.github/pins/ipex.txt)"
        echo "IPEX_REPO=${{ inputs.repository }}" >> "$GITHUB_ENV"
        echo "IPEX_COMMIT_ID=$IPEX_COMMIT_ID" >> "$GITHUB_ENV"

    - name: Identify Python version
      shell: bash
      run: |
        if [[ -z "$PYTHON_VERSION" ]]; then
          PYTHON_VERSION="$(python -c 'import sys; print(f"{sys.version_info[0]}.{ sys.version_info[1]}")')"
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> "$GITHUB_ENV"
        fi

    # IPEX requires setuptools for Python 3.12
    - name: Install setuptools (Python 3.12)
      if: ${{ env.PYTHON_VERSION == '3.12' }}
      shell: bash
      run: |
        pip install setuptools

    - name: Load IPEX wheels from a cache
      id: ipex-cache
      uses: ./.github/actions/load
      env:
        # Increase this value to reset cache
        CACHE_NUMBER: 4
      with:
        path: intel-extension-for-pytorch/dist
        key: ipex-$PYTHON_VERSION-$IPEX_COMMIT_ID-$CACHE_NUMBER

    - name: Clone IPEX repository
      if: ${{ steps.ipex-cache.outputs.status == 'miss' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ env.IPEX_COMMIT_ID }}
        submodules: recursive
        path: intel-extension-for-pytorch

    - name: Build IPEX
      if: ${{ steps.ipex-cache.outputs.status == 'miss' }}
      shell: bash
      run: |
        source ${{ inputs.oneapi }}/setvars.sh
        export USE_AOT_DEVLIST='pvc'
        cd intel-extension-for-pytorch
        pip install wheel
        pip install -r requirements.txt
        python setup.py bdist_wheel

    - name: Install IPEX
      shell: bash
      run: |
        source ${{ inputs.oneapi }}/setvars.sh
        pip install intel-extension-for-pytorch/dist/*.whl
        IPEX_VERSION="$(python -c 'import torch;import intel_extension_for_pytorch as ipex;print(ipex.__version__)')"
        echo "IPEX_VERSION=$IPEX_VERSION" | tee -a "$GITHUB_ENV"

    - name: Save IPEX wheels to a cache
      if: ${{ steps.ipex-cache.outputs.status == 'miss' }}
      uses: ./.github/actions/save
      with:
        path: ${{ steps.ipex-cache.outputs.path }}
        dest: ${{ steps.ipex-cache.outputs.dest }}
