"""
Regression test for FP8E4M3FN -> FP16 conversion.

Guards the fmul-based converter that replaces the 22-op lookup table with a
short bit-manipulation-plus-multiply sequence. Validates the conversion
across all 256 possible fp8 byte values, including NaN propagation for the
two reserved fp8e4m3 NaN encodings (0x7F, 0xFF).

Converter algorithm:
1. Sign-extend each fp8 byte to i16 and shift it left by 7.
2. Mask the shifted value with 0xBFFF.
3. Multiply by 36864.0, then by 0.0069427490234375. The first multiply is
   deliberately chosen to overflow to +/-Inf only for the two reserved NaN
   byte encodings (0x7F, 0xFF); all 254 finite bytes remain bit-identical to
   the previous <<7 + *256.0 converter.
4. Compute y + y*0.0. For finite y this is a no-op; for the Inf produced in
   step 3 this yields NaN (Inf*0.0 -> NaN, then Inf + NaN -> NaN), which is
   how the two reserved bytes end up propagating to NaN.

The NaN produced in step 4 is generated by hardware (Inf*0.0 + Inf), so its
sign and payload are hardware-dependent. Only BMG/B580 has been measured
(0xFE00, with the input sign bit discarded). This test therefore checks
`isnan` for those two bytes rather than a specific bit pattern.

NOTE: under TRITON_INTEL_FAST_MATH=1, the emitted ops carry fast-math flags,
which license LLVM to fold away `y + y*0.0` and/or reassociate the two
rebias multiplies (36864.0 * 0.0069427490234375 == 255.9375, which does not
overflow). The outcome for the two reserved bytes in that mode is therefore
unspecified by this test (it has been observed as +/-Inf, but a finite
result is also permitted) -- this test exercises only the default,
non-fast-math converter and is not valid under TRITON_INTEL_FAST_MATH=1. It
has no skip for that mode because the test suite does not set that env var
by default.

NOTE: This test validates the SOFTWARE fallback converter (used on PVC/Max).
On Xe3P+ with ttig.support_f8_conversion, the SPIR-V builtin path is used
instead and this test does not exercise that path.
"""
import struct
import numpy as np
import pytest
import torch
import triton
import triton.language as tl
from triton._internal_testing import is_xpu


def expected_fp16_for_byte(byte: int) -> int:
    """
    Reference implementation for the 254 FINITE fp8e4m3 byte values.

    Returns the fp16 bit pattern (uint16) that the Triton converter produces
    for the given fp8 byte value. This model does NOT apply to the two
    reserved NaN byte encodings (0x7F, 0xFF) -- see `is_fp16_nan` and the
    module docstring for how those two bytes are checked instead.

    Algorithm:
    1. Strip sign: u = byte & 0x7F
    2. Shift to fp16 layout: shifted = u << 7
       - fp8: 1 sign + 4 exp + 3 mantissa
       - fp16: 1 sign + 5 exp + 10 mantissa
       - After <<7, bits land at fp16 positions with exp bias still 7
    3. Multiply by 256.0 (2^8) to rebias from 7 to 15
       - For normals: (1 + m/8) * 2^(e-7) * 256 = (1 + m/8) * 2^(e+1)
       - For subnormals: same multiplier works due to mantissa position
    4. Restore sign bit from byte bit 7 to fp16 bit 15

    NOTE: this shift-and-multiply model is bit-identical to the new
    converter's output on all 254 finite bytes (see module docstring); only
    the two reserved bytes differ between the old and new converters.
    """
    # Strip sign, take 7 bits of exp+mantissa
    u = byte & 0x7F
    sign_bit = (byte & 0x80) << 8
    # Shift to align with fp16 layout
    shifted = (u << 7) & 0xFFFF
    # Bitcast to fp16
    h_in = struct.unpack('<e', struct.pack('<H', shifted))[0]
    # Multiply by 256.0 to rebias exponent from 7 to 15
    mul = np.float16(256.0)
    h_out = float(np.float16(h_in) * mul)
    out_bits = struct.unpack('<H', struct.pack('<e', h_out))[0]
    # Restore sign bit: byte bit 7 -> fp16 bit 15
    return (out_bits | sign_bit) & 0xFFFF


# The two reserved fp8e4m3 byte encodings (sign | exp=1111 | mantissa=111).
# The converter propagates these to a hardware-generated NaN rather than a
# finite value; the NaN sign/payload is hardware-dependent (see module
# docstring), so these bytes are checked via `is_fp16_nan` instead of
# `expected_fp16_for_byte`.
RESERVED_NAN_BYTES = (0x7F, 0xFF)


def is_fp16_nan(bits: int) -> bool:
    """Return True if the fp16 bit pattern encodes a NaN (biased exponent
    all-ones and a non-zero mantissa)."""
    exponent = (bits >> 10) & 0x1F
    mantissa = bits & 0x3FF
    return exponent == 0x1F and mantissa != 0


@triton.jit
def fp8_to_fp16_kernel(src_ptr, dst_ptr, BLOCK: tl.constexpr):
    """Convert FP8E4M3FN to FP16 via tl.cast."""
    offs = tl.arange(0, BLOCK)
    x = tl.load(src_ptr + offs)
    y = x.to(tl.float16)
    tl.store(dst_ptr + offs, y)


@pytest.mark.skipif(not is_xpu(), reason="XPU-specific test")
def test_fp8e4m3fn_to_fp16_all_bytes(device):
    """
    Exhaustive test of all 256 FP8E4M3FN byte values.

    Validates bit-exact conversion to FP16 against the reference
    implementation for the 254 finite byte values (see module docstring for
    the converter algorithm). The two reserved NaN byte encodings (0x7F,
    0xFF) are validated for NaN-ness only, since their sign/payload is
    hardware-dependent.

    This test ensures no regressions in the conversion path.
    """
    # Allocate 256 input bytes covering all possible fp8 values
    src_uint8 = torch.arange(256, dtype=torch.uint8, device=device)
    src = triton.reinterpret(src_uint8, torch.float8_e4m3fn)
    dst = torch.empty(256, dtype=torch.float16, device=device)

    # Launch kernel with BLOCK=256 (single workgroup)
    fp8_to_fp16_kernel[(1, )](src, dst, BLOCK=256)

    # Convert output to uint16 for bit-exact comparison
    dst_bits = dst.view(torch.uint16).cpu().tolist()

    # Check for mismatches. The 254 finite bytes are compared bit-exactly
    # against the reference model; the two reserved NaN bytes (0x7F, 0xFF)
    # are only checked for NaN-ness, since their sign/payload is
    # hardware-dependent (see module docstring).
    mismatches = []
    for b in range(256):
        got = dst_bits[b]
        if b in RESERVED_NAN_BYTES:
            if not is_fp16_nan(got):
                mismatches.append((b, "NaN", got))
            continue
        expected = expected_fp16_for_byte(b)
        if expected != got:
            mismatches.append((b, expected, got))

    if mismatches:
        # Format up to 20 mismatches for diagnostics
        msg = '\n'.join(f"  byte=0x{b:02x} expected={e if isinstance(e, str) else f'0x{e:04x}'} got=0x{g:04x}"
                        for b, e, g in mismatches[:20])
        total = len(mismatches)
        if total > 20:
            msg += f"\n  ... and {total - 20} more mismatches"
        pytest.fail(f"{total} bytes mismatched (out of 256):\n{msg}")


@pytest.mark.skipif(not is_xpu(), reason="XPU-specific test")
@pytest.mark.parametrize("op_idx", [0, 1])
@pytest.mark.parametrize("k", [32, 64])
@pytest.mark.parametrize("block_io", ["row_major", "column_major"])
def test_fp8e4m3fn_to_fp16_dot_operand(op_idx, k, block_io, device, tmp_path):
    """Exhaustive FP8E4M3FN -> FP16 conversion in dot operand layouts loaded by 2D block loads."""
    shape = (1024 // k, k) if op_idx == 0 else (k, 1024 // k)
    src_shape = shape[::-1] if block_io == "column_major" else shape
    src_ty = f"{src_shape[0]}x{src_shape[1]}xf8E4M3FN"
    fp8_ty = f"{shape[0]}x{shape[1]}xf8E4M3FN"
    f16_ty = f"{shape[0]}x{shape[1]}xf16"
    support_block_io = triton.runtime.driver.active.get_current_target().arch['has_2d_block_io']

    ir = f"""
    #dpas = #ttig.dpas<{{repeatCount = 8, systolicDepth = 8, executionSize = 16, opsPerChan = 2, threadsPerWarp = 16, warpsPerCTA = [1, 1], repCluster = [1, 1], A = [8, 16], B = [16, 16], C = [8, 16]}}>
    #dot = #ttg.dot_op<{{opIdx = {op_idx}, parent = #dpas, kWidth = {2 if op_idx == 1 else 1}}}>
    module attributes {{{"ttig.support_2d_block_io, " if support_block_io else ""}"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 1 : i32, ttg.target = "xpu", "ttg.threads-per-warp" = 16 : i32}} {{
      tt.func public @fp8_to_fp16(%src: !tt.ptr<f8E4M3FN> {{tt.divisibility = 16 : i32}}, %dst: !tt.ptr<f16> {{tt.divisibility = 16 : i32}}) {{
        %c0_i32 = arith.constant 0 : i32
        %c1_i64 = arith.constant 1 : i64
        %src_rows = arith.constant {src_shape[0]} : i32
        %src_cols = arith.constant {src_shape[1]} : i32
        %src_stride = arith.constant {src_shape[1]} : i64
        %dst_rows = arith.constant {shape[0]} : i32
        %dst_cols = arith.constant {shape[1]} : i32
        %dst_stride = arith.constant {shape[1]} : i64
        %src_desc = tt.make_tensor_descriptor %src, [%src_rows, %src_cols], [%src_stride, %c1_i64] : !tt.ptr<f8E4M3FN>, !tt.tensordesc<{src_ty}>
        %x = tt.descriptor_load %src_desc[%c0_i32, %c0_i32] {{ttig.block_io = "{block_io}", ttig.desc_padding = 1 : i32}} : !tt.tensordesc<{src_ty}> -> tensor<{fp8_ty}, #dot>
        %y = tt.fp_to_fp %x : tensor<{fp8_ty}, #dot> -> tensor<{f16_ty}, #dot>
        %dst_desc = tt.make_tensor_descriptor %dst, [%dst_rows, %dst_cols], [%dst_stride, %c1_i64] : !tt.ptr<f16>, !tt.tensordesc<{f16_ty}>
        tt.descriptor_store %dst_desc[%c0_i32, %c0_i32], %y : !tt.tensordesc<{f16_ty}>, tensor<{f16_ty}, #dot>
        tt.return
      }}
    }}
    """

    # Every byte value at every byte position of a 32-bit word.
    i = torch.arange(1024)
    src = ((i // 4 + 64 * (i % 4)) % 256).to(torch.uint8).reshape(src_shape)
    dst = torch.full(shape, float("inf"), dtype=torch.float16, device=device)

    temp_file = tmp_path / "fp8e4m3fn_to_fp16_dot_operand.ttgir"
    temp_file.write_text(ir)
    kernel = triton.compile(str(temp_file))
    kernel[(1, 1, 1)](src.to(device).view(torch.float8_e4m3fn), dst)

    if support_block_io:
        llir = kernel.asm["llir"]
        assert llir.count("spirv_Subgroup2DBlockLoad") + llir.count("GenISA.LSC2DBlockRead") > 0

    loaded = (src.T if block_io == "column_major" else src).to(torch.int64)
    nan = torch.isin(loaded, torch.tensor(RESERVED_NAN_BYTES))
    expected = torch.tensor([expected_fp16_for_byte(b) for b in range(256)])[loaded]
    got = dst.cpu().view(torch.int16).to(torch.int64) & 0xFFFF
    torch.testing.assert_close(got[~nan], expected[~nan])
    assert dst.cpu()[nan].isnan().all()
