name: Build and test upstream pytorch with no IPEX
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      runner_label:
        description: Runner label, keep empty for default
        type: string
        default: ""
      pytorch_ref:
        description: PyTorch ref, keep empty for default
        type: string
        default: ""
      upload_test_reports:
        description: Upload test reports
        type: boolean
        default: false
      ignore_errors:
        description: Ignore test errors
        type: boolean
        default: false
      skip_list:
        description: Skip list
        type: string
        default: ""
      run_name:
        description: Custom run name
        type: string
        default: "Build and test upstream pytorch with no IPEX"
      enable_unskip:
        description: Ignore pytest.skip
        type: boolean
        default: false

permissions: read-all

jobs:
  integration-tests:
    name: Integration tests matrix
    strategy:
      matrix:
        python: ["3.9"]
        driver: ["rolling", "lts"]
      fail-fast: false
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      driver_version: ${{ matrix.driver }}
      runner_label: ${{ inputs.runner_label }}
      install_ipex: false
      pytorch_ref: ${{ inputs.pytorch_ref }}
      python_version: ${{ matrix.python }}
      upload_test_reports: ${{ inputs.upload_test_reports || false }}
      ignore_errors: ${{ inputs.ignore_errors || false }}
      skip_list: ${{ inputs.skip_list }}
      run_name: ${{ inputs.run_name }}
      enable_unskip: ${{ inputs.enable_unskip || false }}
