name: Build and test on A770
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      runner_label:
        description: Runner label, keep empty for default
        type: string
        default: "a770"
      install_ipex:
        # This boolean parameter defines what PyTorch will be used in the workflow:
        #   true: Stonepia/pytorch (fork) with IPEX
        #   false: pytorch/pytorch (upstream) without IPX
        # In both cases, pytorch_ref below allows specifying a branch, tag, or commit id in the
        # corresponding repository. If not specified, a default (pinned) version will be used.
        description: Install Intel PyTorch Extension
        type: boolean
        default: true
      pytorch_ref:
        description: PyTorch ref, keep empty for default
        type: string
        default: ""
      upload_test_reports:
        description: Upload test reports
        type: boolean
        default: false
      ignore_errors:
        description: Ignore test errors
        type: boolean
        default: false
      run_name:
        description: Custom run name
        type: string
        default: "Build and test on A770"
  schedule:
    # Every midnight PST (UTC-8)
    - cron: "0 8 * * *"

permissions: read-all

jobs:
  integration-tests:
    name: Integration tests matrix
    strategy:
      matrix:
        python: ${{ github.ref_name == 'llvm-target' && fromJson('["3.9", "3.10", "3.11"]') || fromJson('["3.9"]') }}
        drivers: ["rolling", "lts"]
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      driver_version: ${{ matrix.drivers }}
      runner_label: ${{ inputs.runner_label || 'a770' }}
      install_ipex: ${{ inputs.install_ipex || github.event_name == 'schedule' }}
      pytorch_ref: ${{ inputs.pytorch_ref }}
      python_version: ${{ matrix.python }}
      upload_test_reports: ${{ inputs.upload_test_reports }}
      ignore_errors: ${{ inputs.ignore_errors }}
      run_name: ${{ inputs.run_name }}
