name: Build and test upstream pytorch with no IPEX
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      runner_label:
        description: Runner label, keep empty for default
        type: string
        default: ""
      pytorch_ref:
        description: PyTorch ref, keep empty for default
        type: string
        default: ""
      upload_test_reports:
        description: Upload test reports
        type: boolean
        default: false
      ignore_errors:
        description: Ignore test errors
        type: boolean
        default: false
      run_name:
        description: Custom run name
        type: string
        default: "Build and test upstream pytorch with no IPEX"
  schedule:
    # Every midnight PST (UTC-8)
    - cron: "0 8 * * *"

permissions: read-all

jobs:
  integration-tests:
    name: Integration tests matrix
    strategy:
      matrix:
        python: ${{ github.ref_name == 'llvm-target' && fromJson('["3.9", "3.10", "3.11"]') || fromJson('["3.9"]') }}
        drivers: ["rolling", "lts"]
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      driver_version: ${{ matrix.drivers }}
      runner_label: ${{ inputs.runner_label }}
      install_ipex: false
      pytorch_ref: ${{ inputs.pytorch_ref }}
      python_version: ${{ matrix.python }}
      upload_test_reports: ${{ inputs.upload_test_reports || false }}
      ignore_errors: ${{ inputs.ignore_errors || false }}
      run_name: ${{ inputs.run_name }}
