name: Run nightly profiling tests of llama kernels on JGS and CRI simulators
run-name: ${{ inputs.run_name }}

on:
  workflow_dispatch:
    inputs:
      run_name:
        description: Custom run name
        type: string
        default: "Llama kernels profiling on simulators"

  schedule:
    - cron: '0 5 * * *' # every day at 5 AM UTC, which is 11 PM CST or 12 AM CDT

env:
  DEVICES: "jgs cri"

jobs:
  build-and-test:
    name: Profiling tests matrix
    strategy:
      fail-fast: false
      matrix:
        device:
          - jgs
          - cri

    uses: intel-tools/intel-xpu-backend-for-triton/.github/workflows/llama-kernels-simulator-profiling-nightly-reusable.yml@main-interim
    secrets: inherit
    with:
      device: ${{ matrix.device }}
