name: Triton wheels

on:
  workflow_dispatch:
  schedule:
    - cron: "5 23 * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/nightly-wheels.yml
      - .github/pins/pytorch.txt
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/nightly-wheels.yml
      - .github/pins/pytorch.txt

permissions: read-all

env:
  USE_AOT_DEVLIST: pvc

jobs:
  build:
    name: Build
    runs-on:
      - max1100
      - rolling
      - runner-0.0.22
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
      fail-fast: false
      max-parallel: 2
    defaults:
      run:
        shell: bash -noprofile --norc -eo pipefail -c "source /opt/intel/oneapi/setvars.sh > /dev/null; source {0}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: 'release/3.7.1'

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python build dependencies
        run: |
          # cmake 3.22.1 does not work with the recent torchaudio: https://github.com/intel/intel-xpu-backend-for-triton/issues/2079
          pip install cmake build

      - name: Identify Triton commit id
        run: |
          echo "TRITON_COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Build Triton wheels
        uses: ./.github/actions/setup-triton
        with:
          command: >
            DEBUG=1
            python -m build --wheel --no-isolation && pip install dist/*.whl

      - name: Prepare wheels for upload
        run: |
          mkdir -p wheels
          cp -L dist/*.whl wheels/
          ls -lh wheels/

      - name: Report environment details
        run: |
          TIMESTAMP=$(date '+%Y%m%d')
          echo "TIMESTAMP=$TIMESTAMP" >> "${GITHUB_ENV}"

          cat <<EOF | tee wheels/.env
          TIMESTAMP=$TIMESTAMP
          GITHUB_RUN_ID=$GITHUB_RUN_ID
          GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER
          GITHUB_RUN_ATTEMPT=$GITHUB_RUN_ATTEMPT
          PYTHON_VERSION=$PYTHON_VERSION
          LLVM_REPO=llvm/llvm-project
          LLVM_COMMIT_ID=$LLVM_COMMIT_ID
          TRITON_REPO=intel/intel-xpu-backend-for-triton
          TRITON_COMMIT_ID=$TRITON_COMMIT_ID
          EOF

      - name: Upload Triton wheels to artifacts
        uses: actions/upload-artifact@v7
        with:
          name: triton-release-wheels-py${{ matrix.python }}-${{ env.TIMESTAMP }}
          path: wheels
          include-hidden-files: true
