name: Nightly merge main-interim into main-cri
run-name: Nightly merge main-interim into main-cri

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 2-4' # Every day at 9:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  do-merge:
    if: ${{ github.ref == 'refs/heads/main-interim' }}
    name: Do the merge
    runs-on:
      - cri
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout main-cri branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main-cri

      - name: Do merge in a new branch and create PR
        env:
          GH_TOKEN: ${{ secrets.GLADOS_TOKEN }}
        run: |
          set -xe

          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BRANCH_NAME=merge-main-interim-${TIMESTAMP}

          git config user.name "GlaDOS"
          git config user.email "glados@intel.com"
          git config merge.ours.driver true

          git checkout -b "${BRANCH_NAME}" main-cri
          git fetch origin main-interim:main-interim
          git merge --verbose --commit --no-edit -m "AUTOMERGE main-interim into main-cri" --no-ff --no-squash --stat main-interim
          git push origin "${BRANCH_NAME}"
          TOP_COMMIT=$(git rev-parse --short HEAD)

          gh pr create \
            --repo intel-tools/intel-xpu-backend-for-triton \
            --title "[CRI] AUTOMERGE main-interim into main-cri commit ${TOP_COMMIT}" \
            --body "Automated merge of main-interim into main-cri. Do not squash!" \
            --reviewer gshimansky,whitneywhtsang \
            --base main-cri \
            --head "${BRANCH_NAME}"

          gh api repos/intel-tools/intel-xpu-backend-for-triton -X PATCH -f allow_merge_commit=true
          gh pr merge --repo intel-tools/intel-xpu-backend-for-triton --merge --auto "${BRANCH_NAME}"
          gh api repos/intel-tools/intel-xpu-backend-for-triton -X PATCH -f allow_merge_commit=false
