name: Third party benchmarks, BMG

permissions: read-all

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build-wheel:
    uses: ./.github/workflows/build-benchmarks-wheel.yml
    with:
      python-version: "3.12"

  benchmarks:
    needs: build-wheel
    if: always() && !cancelled()
    uses: ./.github/workflows/third-party-benchmarks.yml
    with:
      runner_label: b580
      benchmarks: '["sglang"]'
    secrets: inherit
