name: Third party benchmarks, BMG

permissions: read-all

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  benchmarks:
    uses: ./.github/workflows/third-party-benchmarks.yml
    with:
      runner_label: b580
      benchmarks: '["sglang"]'
    secrets: inherit
