name: Triton benchmarks, PVC

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/triton-benchmarks*.yml
      - .github/workflows/build-benchmarks-wheel*.yml
      - .github/actions/install-benchmarks/**
      - benchmarks/**
      - '!benchmarks/triton_kernels_benchmark/vllm/**'
      - '!benchmarks/triton_kernels_benchmark/sglang/**'
      - .github/pins/pytorch.txt

jobs:
  build-wheel:
    uses: ./.github/workflows/build-benchmarks-wheel.yml
    with:
      python-version: "3.12"

  benchmarks:
    needs: build-wheel
    if: always() && !cancelled()
    uses: ./.github/workflows/triton-benchmarks.yml
    with:
      runner_label: max1550
      skip_benchmarks: "[]"
