name: Triton benchmarks, BMG

permissions: read-all

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      benchmarks: ${{ steps.filter.outputs.benchmarks }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            benchmarks:
              - '.github/workflows/triton-benchmarks*.yml'
              - 'benchmarks/**'

  benchmarks:
    needs: check-paths
    if: needs.check-paths.outputs.benchmarks == 'true' || github.event.label.name == 'run-benchmarks'
    uses: ./.github/workflows/triton-benchmarks.yml
    with:
      runner_label: b580
      skip_benchmarks: "['flex_attention_benchmark_batch16-causal_mask.py']"
