name: Get the latest commit from SPIRV-LLVM-Translator

on:
#   schedule:
#     - cron: "0 0 * * *"
  pull_request:
    branches:
      - lijunhui/translator_cid
  push:
    branches:
      - lijunhui/translator_cid

jobs:
  update-translator-commit:
    runs-on:
      - glados
      - spr
      - runner-0.0.18
    defaults:
      run:
        shell: bash -noprofile --norc -eo pipefail -c "source /home/runner/intel/oneapi/setvars.sh > /dev/null; source {0}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load pip cache
        id: pip-cache
        uses: ./.github/actions/load
        env:
          # Increase this value to reset cache
          CACHE_NUMBER: 1
        with:
          path: $HOME/.cache/pip
          key: pip-3.10-${{ hashFiles('python/pyproject.toml', 'python/setup.py') }}-${{ env.CACHE_NUMBER }}

      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup PyTorch with IPEX
        uses: ./.github/actions/setup-pytorch
        with:
          repository: Stonepia/pytorch
          ref: ""

      - name: Setup IPEX
        uses: ./.github/actions/setup-ipex

      - name: Install test dependencies
        run: |
          pip install pytest pytest-xdist pytest-rerunfailures pytest-select pytest-timeout expecttest
          pip install git+https://github.com/kwasd/pytest-capturewarnings-ng.git@v1.2.0

      - name: Get commit ID from Triton's spirv-llvm-translator.conf
        id: translator-commit-in-triton
        run: echo "cid_current=$(cat ./lib/Target/SPIRV/spirv-llvm-translator.conf)" >> $GITHUB_ENV

      - name: Checkout SPIRV-LLVM-Translator
        uses: actions/checkout@v4
        with:
          repository: KhronosGroup/SPIRV-LLVM-Translator
          ref: main
          fetch-depth: 0
          path: external/SPIRV-LLVM-Translator

      - name: Get the latest commit ID from SPIRV-LLVM-Translator
        id: translator-latest-commit
        run: |
          echo "cid_latest=$(git -C external/SPIRV-LLVM-Translator rev-parse HEAD)" >> $GITHUB_ENV

      - name: Run check_update.sh
        run: |
          ./scripts/check_update_tranlator_cid.sh ${{ env.cid_latest }} ${{ env.cid_current }}
