name: vLLM benchmarks, BMG

permissions: read-all

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  benchmarks:
    uses: ./.github/workflows/vllm-benchmarks.yml
    with:
      runner_label: b580
    secrets: inherit
