name: vLLM benchmarks

on:
  workflow_dispatch:
    inputs:
      runner_label:
        description: Runner label, keep empty for default
        type: string
        default: ""
      tag:
        description: Tag for benchmark results
        type: string
        default: "test"
      vllm_pin:
        description: vLLM pin (commit hash), keep empty for default
        type: string
        default: ""
  # This workflow is also called from workflows vllm-benchmarks-*.yml.
  workflow_call:
    inputs:
      runner_label:
        description: Runner label
        type: string
      tag:
        description: Tag for benchmark results
        type: string
        default: "test"
      vllm_pin:
        description: vLLM pin (commit hash), keep empty for default
        type: string
        default: ""

  schedule:
    - cron: "0 8 * * *"

permissions: read-all

# VLLM installation from upstream uses vllm-xpu-kernels wheel which is built just for python==3.12
env:
  PYTHON_VERSION: "3.12"
  TAG: ${{ inputs.tag || (github.event_name == 'pull_request' && format('pr-{0}', github.event.number)) || (github.event_name == 'schedule' && 'ci') || 'test' }}
  HF_TOKEN: ${{ secrets.HF_TOKEN || '' }}

jobs:
  build:
    name: vLLM benchmarks
    runs-on:
      - linux
      - ${{ inputs.runner_label || 'max1550' }}
    timeout-minutes: 720
    defaults:
      run:
        shell: bash -noprofile --norc -eo pipefail -c "source /opt/intel/oneapi/setvars.sh > /dev/null; source {0}"
    steps:
      - name: Print inputs
        run: |
          cat <<EOF
          ${{ toJSON(inputs) }}
          EOF

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Override vLLM pin
        if: ${{ inputs.vllm_pin }}
        run: |
          echo "${{ inputs.vllm_pin }}" > benchmarks/vllm/vllm-pin.txt
          echo "Overriding vLLM pin to: ${{ inputs.vllm_pin }}"

      - name: Install Python (from pyenv) ${{ inputs.python_version }}
        uses: ./.github/actions/setup-pyenv-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Identify Python version
        run: |
          PYTHON_VERSION="$(python -c 'import sys; print(f"{sys.version_info[0]}.{ sys.version_info[1]}")')"
          echo "PYTHON_VERSION=$PYTHON_VERSION" | tee -a $GITHUB_ENV

      - name: Install Python build dependencies
        run: |
          pip install cmake

      - name: Setup PyTorch
        uses: ./.github/actions/setup-pytorch

      - name: Setup Triton
        uses: ./.github/actions/setup-triton

      - name: Create reports dir
        run: |
          mkdir reports
          echo "REPORTS=$PWD/reports" >> $GITHUB_ENV

      - name: Install benchmark dependencies
        id: install
        run: |
          pip install transformers 'pandas<3.0' pytest

      - name: Install benchmarks
        id: install-benchmarks
        run: |
          cd benchmarks
          # --no-build-isolation is necessary after moving to python=3.12
          pip install --no-build-isolation .

      - name: Install vllm
        id: install-vllm
        if: ${{ steps.install-benchmarks.outcome == 'success' && !cancelled() }}
        run: |
          source ./scripts/capture-hw-details.sh
          ./scripts/test-triton.sh --install-vllm --skip-pip-install --skip-pytorch-install

      - name: Run vllm unified attention bf16
        if: ${{ steps.install-vllm.outcome == 'success' && !cancelled() }}
        run: |
          source ./scripts/capture-hw-details.sh

          cd benchmarks/vllm
          bash run_benchmark.sh unified_attention --reports $REPORTS
          # Transform baseline results
          python transform_results.py \
            $REPORTS/unified-attention-performance.csv \
            $REPORTS/unified-attention-report.csv \
            --tag $TAG \
            --bgroup "vllm" \
            --benchmark "unified-attn-bf16" \
            --param_cols "q_heads,k_heads,head_size,qdtype,seq_lens,sliding_window,soft_cap,num_blocks,block_size"
          # Transform tensor descriptor patched results
          python transform_results.py \
            $REPORTS/unified-attention-performance-td.csv \
            $REPORTS/unified-attention-td-report.csv \
            --tag $TAG \
            --bgroup "vllm" \
            --benchmark "unified-attn-bf16" \
            --param_cols "q_heads,k_heads,head_size,qdtype,seq_lens,sliding_window,soft_cap,num_blocks,block_size"

      - name: Run vllm unified attention fp8
        if: ${{ steps.install-vllm.outcome == 'success' && !cancelled() }}
        run: |
          source ./scripts/capture-hw-details.sh

          cd benchmarks/vllm
          FP8="1" bash run_benchmark.sh unified_attention --reports $REPORTS
          # Transform baseline results
          python transform_results.py \
            $REPORTS/unified-attention-performance.csv \
            $REPORTS/unified-attention-fp8-report.csv \
            --tag $TAG \
            --bgroup "vllm" \
            --benchmark "unified-attn-fp8" \
            --param_cols "q_heads,k_heads,head_size,qdtype,seq_lens,sliding_window,soft_cap,num_blocks,block_size"
          # Transform tensor descriptor patched results
          python transform_results.py \
            $REPORTS/unified-attention-performance-td.csv \
            $REPORTS/unified-attention-fp8-td-report.csv \
            --tag $TAG \
            --bgroup "vllm" \
            --benchmark "unified-attn-fp8" \
            --param_cols "q_heads,k_heads,head_size,qdtype,seq_lens,sliding_window,soft_cap,num_blocks,block_size"

      - name: Run vllm batched moe bf16
        if: ${{ steps.install-vllm.outcome == 'success' && !cancelled() }}
        run: |
          source ./scripts/capture-hw-details.sh

          cd benchmarks/vllm
          bash run_benchmark.sh batched_moe --reports $REPORTS
          # Transform baseline results
          python transform_results.py \
            $REPORTS/moe-gemm-performance.csv \
            $REPORTS/moe-gemm-report.csv \
            --tag $TAG \
            --bgroup vllm \
            --benchmark moe-bf16-benchmark \
            --param_cols="num_experts,max_tokens_per_expert,K,N"
          # Transform tensor descriptor patched results
          python transform_results.py \
            $REPORTS/moe-gemm-performance-td.csv \
            $REPORTS/moe-gemm-td-report.csv \
            --tag $TAG \
            --bgroup vllm \
            --benchmark moe-bf16-benchmark \
            --param_cols="num_experts,max_tokens_per_expert,K,N"


      - name: Run vllm batched moe fp8
        if: ${{ steps.install-vllm.outcome == 'success' && !cancelled() }}
        run: |
          source ./scripts/capture-hw-details.sh

          cd benchmarks/vllm
          FP8="1" bash run_benchmark.sh batched_moe --reports $REPORTS
          # Transform baseline results
          python transform_results.py \
            $REPORTS/moe-gemm-performance.csv \
            $REPORTS/moe-gemm-fp8-report.csv \
            --tag $TAG \
            --bgroup vllm \
            --benchmark moe-fp8-benchmark \
            --param_cols="num_experts,max_tokens_per_expert,K,N"
          # Transform tensor descriptor patched results
          python transform_results.py \
            $REPORTS/moe-gemm-performance-td.csv \
            $REPORTS/moe-gemm-fp8-td-report.csv \
            --tag $TAG \
            --bgroup vllm \
            --benchmark moe-fp8-benchmark \
            --param_cols="num_experts,max_tokens_per_expert,K,N"

      - name: Run vllm fused moe correctness test
        if: ${{ steps.install-vllm.outcome == 'success' && !cancelled() }}
        run: |
          cd benchmarks/vllm/fused_moe
          python test_grouped_gemm.py

      - name: Run vllm fused moe bf16
        if: ${{ steps.install-vllm.outcome == 'success' && !cancelled() }}
        run: |
          source ./scripts/capture-hw-details.sh

          cd benchmarks/vllm/fused_moe
          TD_PATCHED=0 python fused_moe_benchmark.py --reports $REPORTS
          # Transform baseline results
          python ../transform_results.py \
            $REPORTS/fused-moe-gemm-performance.csv \
            $REPORTS/fused-moe-gemm-report.csv \
            --tag $TAG \
            --bgroup vllm \
            --benchmark fused-moe-bf16-benchmark \
            --param_cols="num_tokens,output_hidden_size,hidden_size,num_experts,topk"

      - name: Upload benchmark reports
        if: ${{ steps.install.outcome == 'success' && !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: benchmark-reports
          path: reports
