name: vLLM tests, BMG

permissions: read-all

on:
  schedule:
    # Thursday/Sunday 2:05AM PST (UTC-8) or 3:05AM PDT (UTC-7)
    - cron: "5 10 * * THU"
    - cron: "5 10 * * SUN"

jobs:
  tests:
    uses: ./.github/workflows/vllm-tests-reusable.yml
    with:
      runner_label: b580
